### ISSUE TITLE
Mouse appearance gets stuck with respackopts

### ISSUE THREAD

**Issue by DmanMC** [mrmelon54/draggable_lists#18]
When using respackopts and draggable lists together, if you click on the pack options button, the cursor will switch to vertical arrows and wont switch back until you drag something again

https://github.com/mrmelon54/draggable_lists/assets/86991346/01e6fb09-19ae-4fa3-8d44-ecb8d80e3594

**Comment by mrmelon54** [comment]
Figures lol

**Comment by msfjarvis** [comment]
I'm not 100% confident but it seems the fix for this issue caused another regression where the mouse cursor remains visible when returning to the game from an interaction window such as the player inventory or stonecutter.

I can consistently reproduce this with Draggable Lists 1.0.4, and the problem doesn't exist on 1.0.3. If any more information is required for debugging I'm happy to provide it.

**Comment by mrmelon54** [comment]
oohhhh version drop
