### ISSUE TITLE
Incompatible with Essential server list

### ISSUE THREAD

**Issue by TheCatRiX** [mrmelon54/draggable_lists#3]
There are arrows in server list when using [Essential](https://essential.gg/) and dragging servers not working.

![screenshot](https://github.com/MrMelon54/draggable_lists/assets/58901923/b7286b8e-1d14-482a-b7b3-4e2d43633879)

Also clicking "Featured" tab causes crash. Logs: https://mclo.gs/RnTwwxE

**Comment by MrMelon54** [comment]
Looks like both mods try and edit the same vanilla code

**Comment by Johni0702** [comment]
Essential tries to `ModifyArg` the invocations of `blit` which Draggable Lists [completely replaces](https://github.com/MrMelon54/draggable_lists/blob/05cce2592a46a9be830e71a33e3230d1bd93f517/common/src/main/java/com/mrmelon54/DraggableLists/mixin/server/MixinOnlineServerEntry.java#L75-L97).
Instead of `Redirect`, which only a single mod can use, please consider using `WrapWithCondition` from [MixinExtras](https://github.com/LlamaLad7/MixinExtras) instead. Or, if that's not possible for some reason, consider using `ModifyArg` on one of the two coordinates to simply draw the arrows far off-screen.

**Comment by DeshiDesu** [comment]
Doesn't crash when clicking featured tab. Dragging also works for favorites tab except for featured. I'm on 1.20.1 fabric

**Comment by Johni0702** [comment]
> Doesn't crash when clicking featured tab. Dragging also works for favorites tab except for featured. I'm on 1.20.1 fabric

The latest version of Essential includes a workaround for the issue.

I'd still recommend fixing this properly in DraggableLists because 1) Essential may not be able to keep the workaround indefinitely if it causes issues with other mods, and 2) this isn't specific to Essential, any other mod trying to inject at these methods will have the same issues.
If necessary for testing, you can get the old version of Essential for 1.20.1 Fabric from [here](https://cdn.essential.gg/mods/60ab95754d62e56e515c1b3c/64c400898b045520b2c1c997/fabric_1-20-1.jar).
